extends: airbnb-base
env:
    browser: true
    es6: true
    mocha: true
    node: true
rules:
    indent:
        - 2
        - 2
        - SwitchCase: 1
    no-else-return: 0
    quotes: 0
    no-alert: 0
    jsx-quotes: 0
    new-cap:
        - 2 
        - capIsNewExceptions: 
            - MathJax.Hub.Queue
            - KindEditor
            - Immutable.Range
            - Immutable.Repeat
            - Immutable.Map
            - Immutable.List
            - Immutable.Seq
            - Immutable.Record
            - Deferred
            - MathJax.Hub.Register.MessageHook
    no-console: 0
    arrow-body-style: 0
    prefer-arrow-callback: 0
    func-names: 0
    no-use-before-define: 0
    no-underscore-dangle: 0
    no-mixed-operators: 0
    no-plusplus: 0
    class-methods-use-this: 0
    no-continue: 0
    comma-dangle:
        - 2
        - arrays: only-multiline
          objects: only-multiline
          imports: always-multiline
          exports: always-multiline
          functions: ignore
    import/extensions:
        - 2
        - never
        - scss: always
          css: always
          png: always
          jpg: always
    import/no-named-as-default: 0
    import/no-extraneous-dependencies: 0
    import/no-unresolved: 0
    import/prefer-default-export: 0
    no-param-reassign: 0
    one-var:
        - 0
    prefer-destructuring:
        - 0
    object-curly-newline:
        - 0
    no-return-assign:
        - 0
    arrow-parens:
        - 0
    prefer-template:
        - 0
    no-return-await:
        - 0
    no-await-in-loop: 0
    max-len: 0
    require-yield: 0
    global-require: 0
    quote-props: 0
    object-shorthand: 0
    no-case-declarations: 0
    camelcase: 0
    no-shadow: 0
    no-inner-declarations: 0
    no-loop-func: 0
    no-restricted-globals: 0
    dot-notation: 0
    one-var-declaration-per-line: 0
    no-eval: 0
